---
# handlers file for es
- name: Starting Elasticsearch
  service:
    name: elasticsearch
    state: started

- name: Starting Kibana
  service:
    name: kibana
    state: started

- name: Starting logstash
  service:
    name: logstash
    state: started 
